twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        upload_dir: '%kernel.project_dir%/public/uploads'
        image_dir: '%upload_dir%/images'
        university_logos: '%image_dir%/education/logos/'
        profile_images: '%image_dir%/profile/'
        country_flags: '%image_dir%/countries/'